version: 2
updates:
  - package-ecosystem: npm
    directory: /portfolio-website
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      npm-dependencies:
        patterns:
          - "*"
